### ISSUE TITLE
Problem starting datcat

### ISSUE THREAD

**Issue by dphiffer** [sdockray/dat-cardcat#3]
Here's an error message I'm seeing when I try to start up `datcat`:

```
$ datcat
/Users/dphiffer/Sites/aaarg/dat-cardcat/bin/datcat-run.js:6
let cardcat = false;
^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:442:10)
    at startup (node.js:136:18)
    at node.js:966:3
```

This is on node v4.3.0.

**Comment by e-e-e** [comment]
Ah - this is simply that node 4 does not support es6 features. I suggest updating to node 6.
I would say update babel - but the cli is does not currently get transpired by babel.

I am going to close this issue because we don’t intend to support node 4.

**Comment by e-e-e** [comment]
@dphiffer have you had a look at http://node.green. It’s what originally convinced me to move to v6.
